name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  print_date:
    runs-on: ubuntu-20.04
    steps:
      - name: Now it is
        run: |
          date
  directory_content:
    runs-on: ubuntu-20.04
    steps:
      - name: directory content
        run: |
          ls -l